imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ro
    app.locales: ro|en
    locale_supported: ['ro','en']
    app.categorie: cofetarie|patiserie|torturi
    app.subcategorie: produse-la-kilogram|produse-la-bucata|fursecuri|bomboane|cozonaci|turte|torturi-de-botez|torturi-de-nunta|torturi-pentru-copii

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
#    profiler:
#        collect: false


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Assetic
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

#SonataAdminBundle
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

#create group for sonata admin bundle
sonata_admin:
    title: Cofetaria IOANA
    title_logo: /assets/images/logo_title.png
    dashboard:
        groups:
            Administration:
                icon: '<i class="fa fa-cogs"></i>'
            Category:
                icon: '<i class="fa fa-cogs"></i>'
    templates:
        layout:                         SonataAdminBundle::standard_layout.html.twig
        ajax:                           SonataAdminBundle::ajax_layout.html.twig
        list:                           SonataAdminBundle:CRUD:list.html.twig
        show:                           SonataAdminBundle:CRUD:show.html.twig
        show_compare:                   SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                           SonataAdminBundle:CRUD:edit.html.twig
        history:                        SonataAdminBundle:CRUD:history.html.twig
        preview:                        SonataAdminBundle:CRUD:preview.html.twig
        delete:                         SonataAdminBundle:CRUD:delete.html.twig
        batch:                          SonataAdminBundle:CRUD:list__batch.html.twig
        acl:                            SonataAdminBundle:CRUD:acl.html.twig
        action:                         SonataAdminBundle:CRUD:action.html.twig
        select:                         SonataAdminBundle:CRUD:list__select.html.twig
        filter:                         SonataAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:                      SonataAdminBundle:Core:dashboard.html.twig
        search:                         SonataAdminBundle:Core:search.html.twig
        batch_confirmation:             SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:                 SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:                SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:                     SonataAdminBundle:Block:block_admin_list.html.twig
        user_block:                     SonataAdminBundle:Core:user_block.html.twig
        add_block:                      SonataAdminBundle:Core:add_block.html.twig
        pager_links:                    SonataAdminBundle:Pager:links.html.twig
        pager_results:                  SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:              SonataAdminBundle:Core:tab_menu_template.html.twig
        history_revision_timestamp:     SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:       SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block:            SonataAdminBundle:Block:block_search_result.html.twig
        knp_menu_template:              SonataAdminBundle:Menu:sonata_menu.html.twig

    assets:
        stylesheets:
            # Defaults:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css
        javascripts:
            # Defaults:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
            - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataadmin/treeview.js

    security:
        handler: sonata.admin.security.handler.acl

        #acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

#FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Admin\User

#LiipImageBundle
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        # the name of the "filter set"
        admin_product_image:
            # adjust the image quality to 100%
            quality: 100

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [400, 400], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
               # background: { size: [124, 94], position: center, color: '#000000' }
        admin_choice_image:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        frontEnd_image:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }