<?php

namespace AppBundle\Repository\Admin;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRandomMenuPicture()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Admin\Product p'
            )
            ->getResult();

    }
}
